-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [signal_crypto]: type definitions
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.longLine false
set_option linter.style.setOption false
set_option linter.style.whitespace false
set_option linter.style.nameCheck false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace signal_crypto

/-- [signal_crypto::aes_cbc::EncryptionError]
    Source: 'rust/crypto/src/aes_cbc.rs', lines 13:0-16:1
    Visibility: public -/
@[discriminant isize]
inductive aes_cbc.EncryptionError where
| BadKeyOrIv : aes_cbc.EncryptionError

/-- [signal_crypto::aes_cbc::DecryptionError]
    Source: 'rust/crypto/src/aes_cbc.rs', lines 19:0-24:1
    Visibility: public -/
@[discriminant isize]
inductive aes_cbc.DecryptionError where
| BadKeyOrIv : aes_cbc.DecryptionError
| BadCiphertext : Str → aes_cbc.DecryptionError

end signal_crypto
