-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [libsignal_protocol]: function definitions
import Aeneas
import Libsignal.Translated.RatchetState.Types
import Libsignal.Translated.RatchetState.FunsExternal
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/- You can remove the following line by using the CLI option `-all-computable`: -/
noncomputable section

namespace Libsignal.RatchetState

/-- Trait implementation: [alloc::vec::{impl core::default::Default for alloc::vec::Vec<T>}]
    Source: '/rustc/library/alloc/src/vec/mod.rs', lines 4413:0-4413:32
    Name pattern: [core::default::Default<alloc::vec::Vec<@T>>] -/
@[reducible, rust_trait_impl "core::default::Default<alloc::vec::Vec<@T>>"]
def alloc.vec.Vec.Insts.CoreDefaultDefault (T : Type) : core.default.Default
  (alloc.vec.Vec T) := {
  default := alloc.vec.Vec.Insts.CoreDefaultDefault.default T
}

/-- [libsignal_protocol::consts::MAX_FORWARD_JUMPS]
    Source: 'rust/protocol/src/consts.rs', lines 8:0-8:44
    Visibility: public -/
@[global_simps, irreducible]
def consts.MAX_FORWARD_JUMPS : Std.Usize := 25000#usize

/-- [libsignal_protocol::double_ratchet::INVALID_ROOT_KEY]
    Source: 'rust/protocol/src/double_ratchet.rs', lines 61:0-61:50 -/
@[global_simps, irreducible]
def double_ratchet.INVALID_ROOT_KEY : Str := toStr "invalid root key"

/-- [libsignal_protocol::double_ratchet::INVALID_SENDER_RATCHET_PUBLIC_KEY]
    Source: 'rust/protocol/src/double_ratchet.rs', lines 62:0-62:84 -/
@[global_simps, irreducible]
def double_ratchet.INVALID_SENDER_RATCHET_PUBLIC_KEY : Str :=
  toStr "invalid sender ratchet public key"

/-- [libsignal_protocol::double_ratchet::INVALID_SENDER_RATCHET_PRIVATE_KEY]
    Source: 'rust/protocol/src/double_ratchet.rs', lines 63:0-63:86 -/
@[global_simps, irreducible]
def double_ratchet.INVALID_SENDER_RATCHET_PRIVATE_KEY : Str :=
  toStr "invalid sender ratchet private key"

/-- [libsignal_protocol::double_ratchet::INVALID_CHAIN_KEY]
    Source: 'rust/protocol/src/double_ratchet.rs', lines 64:0-64:52 -/
@[global_simps, irreducible]
def double_ratchet.INVALID_CHAIN_KEY : Str := toStr "invalid chain key"

/-- [libsignal_protocol::ratchet::keys::{libsignal_protocol::ratchet::keys::RootKey}::new]:
    Source: 'rust/protocol/src/ratchet/keys.rs', lines 195:4-197:5 -/
def ratchet.keys.RootKey.new
  (key : Array Std.U8 32#usize) : Result ratchet.keys.RootKey := do
  ok { key }

/-- [libsignal_protocol::ratchet::keys::{libsignal_protocol::ratchet::keys::ChainKey}::new]:
    Source: 'rust/protocol/src/ratchet/keys.rs', lines 155:4-157:5 -/
def ratchet.keys.ChainKey.new
  (key : Array Std.U8 32#usize) (index : Std.U32) :
  Result ratchet.keys.ChainKey
  := do
  ok { key, index }

/-- [libsignal_protocol::double_ratchet::{libsignal_protocol::ratchet::keys::ChainKey}::from_pb::{impl core::ops::function::FnOnce<(core::array::TryFromSliceError,), libsignal_protocol::state::session::InvalidSessionError> for libsignal_protocol::double_ratchet::{libsignal_protocol::ratchet::keys::ChainKey}::from_pb::{closure}}::call_once]:
    Source: 'rust/protocol/src/double_ratchet.rs', lines 210:21-210:63 -/
def
  double_ratchet.ChainKey.from_pb.closure.Insts.CoreOpsFunctionFnOnceTupleTryFromSliceErrorInvalidSessionError.call_once
  (c : double_ratchet.ChainKey.from_pb.closure)
  (tupled_args : core.array.TryFromSliceError) :
  Result state.session.InvalidSessionError
  := do
  ok double_ratchet.INVALID_CHAIN_KEY

/-- Trait implementation: [libsignal_protocol::double_ratchet::{libsignal_protocol::ratchet::keys::ChainKey}::from_pb::{impl core::ops::function::FnOnce<(core::array::TryFromSliceError,), libsignal_protocol::state::session::InvalidSessionError> for libsignal_protocol::double_ratchet::{libsignal_protocol::ratchet::keys::ChainKey}::from_pb::{closure}}]
    Source: 'rust/protocol/src/double_ratchet.rs', lines 210:21-210:63 -/
@[reducible]
def
  double_ratchet.ChainKey.from_pb.closure.Insts.CoreOpsFunctionFnOnceTupleTryFromSliceErrorInvalidSessionError
  : core.ops.function.FnOnce double_ratchet.ChainKey.from_pb.closure
  core.array.TryFromSliceError state.session.InvalidSessionError := {
  call_once :=
    double_ratchet.ChainKey.from_pb.closure.Insts.CoreOpsFunctionFnOnceTupleTryFromSliceErrorInvalidSessionError.call_once
}

/-- [libsignal_protocol::double_ratchet::{libsignal_protocol::ratchet::keys::ChainKey}::from_pb]:
    Source: 'rust/protocol/src/double_ratchet.rs', lines 203:4-212:5 -/
def double_ratchet.ChainKey.from_pb
  (pb : proto.storage.session_structure.chain.ChainKey) :
  Result (core.result.Result ratchet.keys.ChainKey
    state.session.InvalidSessionError)
  := do
  let s ← alloc.vec.Vec.as_slice Global pb.key
  let r ←
    core.array.TryFromArrayCopySlice.try_from 32#usize core.marker.CopyU8 s
  let r1 ←
    core.result.Result.map_err
      double_ratchet.ChainKey.from_pb.closure.Insts.CoreOpsFunctionFnOnceTupleTryFromSliceErrorInvalidSessionError
      r ()
  let cf ← core.result.Result.Insts.CoreOpsTry.branch r1
  match cf with
  | core.ops.control_flow.ControlFlow.Continue val =>
    let ck ← ratchet.keys.ChainKey.new val pb.index
    ok (core.result.Result.Ok ck)
  | core.ops.control_flow.ControlFlow.Break residual =>
    core.result.Result.Insts.CoreOpsTry_traitFromResidualResult.from_residual
      ratchet.keys.ChainKey (core.convert.FromSame
      state.session.InvalidSessionError) residual

/-- [libsignal_protocol::double_ratchet::{libsignal_protocol::double_ratchet::SenderChain}::from_pb::{impl core::ops::function::FnOnce<(libsignal_core::curve::CurveError,), libsignal_protocol::state::session::InvalidSessionError> for libsignal_protocol::double_ratchet::{libsignal_protocol::double_ratchet::SenderChain}::from_pb::{closure#1}}::call_once]:
    Source: 'rust/protocol/src/double_ratchet.rs', lines 176:21-176:80 -/
def
  double_ratchet.SenderChain.from_pb.closure_1.Insts.CoreOpsFunctionFnOnceTupleCurveErrorInvalidSessionError.call_once
  (c : double_ratchet.SenderChain.from_pb.closure_1)
  (tupled_args : libsignal_core.curve.CurveError) :
  Result state.session.InvalidSessionError
  := do
  ok double_ratchet.INVALID_SENDER_RATCHET_PRIVATE_KEY

/-- Trait implementation: [libsignal_protocol::double_ratchet::{libsignal_protocol::double_ratchet::SenderChain}::from_pb::{impl core::ops::function::FnOnce<(libsignal_core::curve::CurveError,), libsignal_protocol::state::session::InvalidSessionError> for libsignal_protocol::double_ratchet::{libsignal_protocol::double_ratchet::SenderChain}::from_pb::{closure#1}}]
    Source: 'rust/protocol/src/double_ratchet.rs', lines 176:21-176:80 -/
@[reducible]
def
  double_ratchet.SenderChain.from_pb.closure_1.Insts.CoreOpsFunctionFnOnceTupleCurveErrorInvalidSessionError
  : core.ops.function.FnOnce double_ratchet.SenderChain.from_pb.closure_1
  libsignal_core.curve.CurveError state.session.InvalidSessionError := {
  call_once :=
    double_ratchet.SenderChain.from_pb.closure_1.Insts.CoreOpsFunctionFnOnceTupleCurveErrorInvalidSessionError.call_once
}

/-- [libsignal_protocol::double_ratchet::{libsignal_protocol::double_ratchet::SenderChain}::from_pb::{impl core::ops::function::FnOnce<(libsignal_core::curve::CurveError,), libsignal_protocol::state::session::InvalidSessionError> for libsignal_protocol::double_ratchet::{libsignal_protocol::double_ratchet::SenderChain}::from_pb::{closure}}::call_once]:
    Source: 'rust/protocol/src/double_ratchet.rs', lines 174:21-174:79 -/
def
  double_ratchet.SenderChain.from_pb.closure.Insts.CoreOpsFunctionFnOnceTupleCurveErrorInvalidSessionError.call_once
  (c : double_ratchet.SenderChain.from_pb.closure)
  (tupled_args : libsignal_core.curve.CurveError) :
  Result state.session.InvalidSessionError
  := do
  ok double_ratchet.INVALID_SENDER_RATCHET_PUBLIC_KEY

/-- Trait implementation: [libsignal_protocol::double_ratchet::{libsignal_protocol::double_ratchet::SenderChain}::from_pb::{impl core::ops::function::FnOnce<(libsignal_core::curve::CurveError,), libsignal_protocol::state::session::InvalidSessionError> for libsignal_protocol::double_ratchet::{libsignal_protocol::double_ratchet::SenderChain}::from_pb::{closure}}]
    Source: 'rust/protocol/src/double_ratchet.rs', lines 174:21-174:79 -/
@[reducible]
def
  double_ratchet.SenderChain.from_pb.closure.Insts.CoreOpsFunctionFnOnceTupleCurveErrorInvalidSessionError
  : core.ops.function.FnOnce double_ratchet.SenderChain.from_pb.closure
  libsignal_core.curve.CurveError state.session.InvalidSessionError := {
  call_once :=
    double_ratchet.SenderChain.from_pb.closure.Insts.CoreOpsFunctionFnOnceTupleCurveErrorInvalidSessionError.call_once
}

/-- [libsignal_protocol::double_ratchet::{libsignal_protocol::double_ratchet::SenderChain}::from_pb]:
    Source: 'rust/protocol/src/double_ratchet.rs', lines 172:4-190:5 -/
def double_ratchet.SenderChain.from_pb
  (chain : proto.storage.session_structure.Chain) :
  Result (core.result.Result double_ratchet.SenderChain
    state.session.InvalidSessionError)
  := do
  let s := alloc.vec.Vec.deref chain.sender_ratchet_key
  let r ← libsignal_core.curve.PublicKey.deserialize s
  let r1 ←
    core.result.Result.map_err
      double_ratchet.SenderChain.from_pb.closure.Insts.CoreOpsFunctionFnOnceTupleCurveErrorInvalidSessionError
      r ()
  let cf ← core.result.Result.Insts.CoreOpsTry.branch r1
  match cf with
  | core.ops.control_flow.ControlFlow.Continue val =>
    let s1 := alloc.vec.Vec.deref chain.sender_ratchet_key_private
    let r2 ← libsignal_core.curve.PrivateKey.deserialize s1
    let r3 ←
      core.result.Result.map_err
        double_ratchet.SenderChain.from_pb.closure_1.Insts.CoreOpsFunctionFnOnceTupleCurveErrorInvalidSessionError
        r2 ()
    let cf1 ← core.result.Result.Insts.CoreOpsTry.branch r3
    match cf1 with
    | core.ops.control_flow.ControlFlow.Continue val1 =>
      let o ← core.option.Option.as_ref chain.chain_key
      let r4 ← core.option.Option.ok_or o (toStr "missing sender chain key")
      let cf2 ← core.result.Result.Insts.CoreOpsTry.branch r4
      match cf2 with
      | core.ops.control_flow.ControlFlow.Continue val2 =>
        let r5 ← double_ratchet.ChainKey.from_pb val2
        let cf3 ← core.result.Result.Insts.CoreOpsTry.branch r5
        match cf3 with
        | core.ops.control_flow.ControlFlow.Continue val3 =>
          ok (core.result.Result.Ok
            {
              ratchet_key := { public_key := val, private_key := val1 },
              chain_key := val3
            })
        | core.ops.control_flow.ControlFlow.Break residual =>
          core.result.Result.Insts.CoreOpsTry_traitFromResidualResult.from_residual
            double_ratchet.SenderChain (core.convert.FromSame
            state.session.InvalidSessionError) residual
      | core.ops.control_flow.ControlFlow.Break residual =>
        core.result.Result.Insts.CoreOpsTry_traitFromResidualResult.from_residual
          double_ratchet.SenderChain (core.convert.FromSame
          state.session.InvalidSessionError) residual
    | core.ops.control_flow.ControlFlow.Break residual =>
      core.result.Result.Insts.CoreOpsTry_traitFromResidualResult.from_residual
        double_ratchet.SenderChain (core.convert.FromSame
        state.session.InvalidSessionError) residual
  | core.ops.control_flow.ControlFlow.Break residual =>
    core.result.Result.Insts.CoreOpsTry_traitFromResidualResult.from_residual
      double_ratchet.SenderChain (core.convert.FromSame
      state.session.InvalidSessionError) residual

/-- [libsignal_protocol::double_ratchet::{libsignal_protocol::double_ratchet::RatchetState}::from_pb::{impl core::ops::function::FnOnce<(&'_0 libsignal_protocol::proto::storage::session_structure::Chain,), core::result::Result<libsignal_protocol::double_ratchet::SenderChain, libsignal_protocol::state::session::InvalidSessionError>> for libsignal_protocol::double_ratchet::{libsignal_protocol::double_ratchet::RatchetState}::from_pb::{closure#1}}::call_once]:
    Source: 'rust/protocol/src/double_ratchet.rs', lines 133:17-133:52 -/
def
  double_ratchet.RatchetState.from_pb.closure_1.Insts.CoreOpsFunctionFnOnceTupleShared0ChainResultSenderChainInvalidSessionError.call_once
  (c : double_ratchet.RatchetState.from_pb.closure_1)
  (tupled_args : proto.storage.session_structure.Chain) :
  Result (core.result.Result double_ratchet.SenderChain
    state.session.InvalidSessionError)
  := do
  double_ratchet.SenderChain.from_pb tupled_args

/-- Trait implementation: [libsignal_protocol::double_ratchet::{libsignal_protocol::double_ratchet::RatchetState}::from_pb::{impl core::ops::function::FnOnce<(&'_0 libsignal_protocol::proto::storage::session_structure::Chain,), core::result::Result<libsignal_protocol::double_ratchet::SenderChain, libsignal_protocol::state::session::InvalidSessionError>> for libsignal_protocol::double_ratchet::{libsignal_protocol::double_ratchet::RatchetState}::from_pb::{closure#1}}]
    Source: 'rust/protocol/src/double_ratchet.rs', lines 133:17-133:52 -/
@[reducible]
def
  double_ratchet.RatchetState.from_pb.closure_1.Insts.CoreOpsFunctionFnOnceTupleShared0ChainResultSenderChainInvalidSessionError
  : core.ops.function.FnOnce double_ratchet.RatchetState.from_pb.closure_1
  proto.storage.session_structure.Chain (core.result.Result
  double_ratchet.SenderChain state.session.InvalidSessionError) := {
  call_once :=
    double_ratchet.RatchetState.from_pb.closure_1.Insts.CoreOpsFunctionFnOnceTupleShared0ChainResultSenderChainInvalidSessionError.call_once
}

/-- [libsignal_protocol::double_ratchet::{libsignal_protocol::double_ratchet::RatchetState}::from_pb::{impl core::ops::function::FnOnce<(core::array::TryFromSliceError,), libsignal_protocol::state::session::InvalidSessionError> for libsignal_protocol::double_ratchet::{libsignal_protocol::double_ratchet::RatchetState}::from_pb::{closure}}::call_once]:
    Source: 'rust/protocol/src/double_ratchet.rs', lines 126:21-126:62 -/
def
  double_ratchet.RatchetState.from_pb.closure.Insts.CoreOpsFunctionFnOnceTupleTryFromSliceErrorInvalidSessionError.call_once
  (c : double_ratchet.RatchetState.from_pb.closure)
  (tupled_args : core.array.TryFromSliceError) :
  Result state.session.InvalidSessionError
  := do
  ok double_ratchet.INVALID_ROOT_KEY

/-- Trait implementation: [libsignal_protocol::double_ratchet::{libsignal_protocol::double_ratchet::RatchetState}::from_pb::{impl core::ops::function::FnOnce<(core::array::TryFromSliceError,), libsignal_protocol::state::session::InvalidSessionError> for libsignal_protocol::double_ratchet::{libsignal_protocol::double_ratchet::RatchetState}::from_pb::{closure}}]
    Source: 'rust/protocol/src/double_ratchet.rs', lines 126:21-126:62 -/
@[reducible]
def
  double_ratchet.RatchetState.from_pb.closure.Insts.CoreOpsFunctionFnOnceTupleTryFromSliceErrorInvalidSessionError
  : core.ops.function.FnOnce double_ratchet.RatchetState.from_pb.closure
  core.array.TryFromSliceError state.session.InvalidSessionError := {
  call_once :=
    double_ratchet.RatchetState.from_pb.closure.Insts.CoreOpsFunctionFnOnceTupleTryFromSliceErrorInvalidSessionError.call_once
}

/-- [libsignal_protocol::double_ratchet::{libsignal_protocol::double_ratchet::RatchetState}::from_pb]:
    Source: 'rust/protocol/src/double_ratchet.rs', lines 117:4-147:5 -/
def double_ratchet.RatchetState.from_pb
  (session : proto.storage.SessionStructure) (self_session : Bool)
  (receiver_chains : alloc.vec.Vec proto.storage.session_structure.Chain) :
  Result (core.result.Result double_ratchet.RatchetState
    state.session.InvalidSessionError)
  := do
  let s ← alloc.vec.Vec.as_slice Global session.root_key
  let r ←
    core.array.TryFromArrayCopySlice.try_from 32#usize core.marker.CopyU8 s
  let r1 ←
    core.result.Result.map_err
      double_ratchet.RatchetState.from_pb.closure.Insts.CoreOpsFunctionFnOnceTupleTryFromSliceErrorInvalidSessionError
      r ()
  let cf ← core.result.Result.Insts.CoreOpsTry.branch r1
  match cf with
  | core.ops.control_flow.ControlFlow.Continue val =>
    let o ← core.option.Option.as_ref session.sender_chain
    let o1 ←
      core.option.Option.map
        double_ratchet.RatchetState.from_pb.closure_1.Insts.CoreOpsFunctionFnOnceTupleShared0ChainResultSenderChainInvalidSessionError
        o ()
    let r2 ← core.option.OptionResult.transpose o1
    let cf1 ← core.result.Result.Insts.CoreOpsTry.branch r2
    match cf1 with
    | core.ops.control_flow.ControlFlow.Continue val1 =>
      let rk ← ratchet.keys.RootKey.new val
      if self_session
      then
        ok (core.result.Result.Ok
          {
            root_key := rk,
            sender_chain := val1,
            receiver_chains,
            previous_counter := session.previous_counter,
            max_forward_jumps := core.num.Usize.MAX
          })
      else
        ok (core.result.Result.Ok
          {
            root_key := rk,
            sender_chain := val1,
            receiver_chains,
            previous_counter := session.previous_counter,
            max_forward_jumps := consts.MAX_FORWARD_JUMPS
          })
    | core.ops.control_flow.ControlFlow.Break residual =>
      core.result.Result.Insts.CoreOpsTry_traitFromResidualResult.from_residual
        double_ratchet.RatchetState (core.convert.FromSame
        state.session.InvalidSessionError) residual
  | core.ops.control_flow.ControlFlow.Break residual =>
    core.result.Result.Insts.CoreOpsTry_traitFromResidualResult.from_residual
      double_ratchet.RatchetState (core.convert.FromSame
      state.session.InvalidSessionError) residual

/-- [libsignal_protocol::ratchet::keys::{libsignal_protocol::ratchet::keys::RootKey}::key]:
    Source: 'rust/protocol/src/ratchet/keys.rs', lines 199:4-201:5 -/
def ratchet.keys.RootKey.impl.key
  (self : ratchet.keys.RootKey) : Result (Array Std.U8 32#usize) := do
  ok self.key

/-- [libsignal_protocol::ratchet::keys::{libsignal_protocol::ratchet::keys::ChainKey}::index]:
    Source: 'rust/protocol/src/ratchet/keys.rs', lines 165:4-167:5 -/
def ratchet.keys.ChainKey.impl.index
  (self : ratchet.keys.ChainKey) : Result Std.U32 := do
  ok self.index

/-- [libsignal_protocol::ratchet::keys::{libsignal_protocol::ratchet::keys::ChainKey}::key]:
    Source: 'rust/protocol/src/ratchet/keys.rs', lines 160:4-162:5 -/
def ratchet.keys.ChainKey.impl.key
  (self : ratchet.keys.ChainKey) : Result (Array Std.U8 32#usize) := do
  ok self.key

/-- [libsignal_protocol::double_ratchet::{libsignal_protocol::ratchet::keys::ChainKey}::to_pb]:
    Source: 'rust/protocol/src/double_ratchet.rs', lines 214:4-219:5 -/
def double_ratchet.ChainKey.to_pb
  (self : ratchet.keys.ChainKey) :
  Result proto.storage.session_structure.chain.ChainKey
  := do
  let i ← ratchet.keys.ChainKey.impl.index self
  let a ← ratchet.keys.ChainKey.impl.key self
  let s ← lift (Array.to_slice a)
  let v ← alloc.slice.Slice.to_vec core.clone.CloneU8 s
  ok { index := i, key := v }

/-- [libsignal_protocol::double_ratchet::{libsignal_protocol::double_ratchet::SenderChain}::to_pb]:
    Source: 'rust/protocol/src/double_ratchet.rs', lines 192:4-199:5 -/
def double_ratchet.SenderChain.to_pb
  (self : double_ratchet.SenderChain) :
  Result proto.storage.session_structure.Chain
  := do
  let s ←
    libsignal_core.curve.PublicKey.serialize self.ratchet_key.public_key
  let v ← alloc.slice.Slice.to_vec core.clone.CloneU8 s
  let v1 ←
    libsignal_core.curve.PrivateKey.serialize self.ratchet_key.private_key
  let s1 := alloc.vec.Vec.deref v1
  let v2 ← alloc.slice.Slice.to_vec core.clone.CloneU8 s1
  let ck ← double_ratchet.ChainKey.to_pb self.chain_key
  ok
    {
      sender_ratchet_key := v,
      sender_ratchet_key_private := v2,
      chain_key := (some ck),
      message_keys :=
        (alloc.vec.Vec.new proto.storage.session_structure.chain.MessageKey)
    }

/-- [libsignal_protocol::double_ratchet::{libsignal_protocol::double_ratchet::RatchetState}::apply_to_pb::{impl core::ops::function::FnOnce<(&'_0 libsignal_protocol::double_ratchet::SenderChain,), libsignal_protocol::proto::storage::session_structure::Chain> for libsignal_protocol::double_ratchet::{libsignal_protocol::double_ratchet::RatchetState}::apply_to_pb::{closure}}::call_once]:
    Source: 'rust/protocol/src/double_ratchet.rs', lines 165:56-165:89 -/
def
  double_ratchet.RatchetState.apply_to_pb.closure.Insts.CoreOpsFunctionFnOnceTupleShared0SenderChainChain.call_once
  (c : double_ratchet.RatchetState.apply_to_pb.closure)
  (tupled_args : double_ratchet.SenderChain) :
  Result proto.storage.session_structure.Chain
  := do
  double_ratchet.SenderChain.to_pb tupled_args

/-- Trait implementation: [libsignal_protocol::double_ratchet::{libsignal_protocol::double_ratchet::RatchetState}::apply_to_pb::{impl core::ops::function::FnOnce<(&'_0 libsignal_protocol::double_ratchet::SenderChain,), libsignal_protocol::proto::storage::session_structure::Chain> for libsignal_protocol::double_ratchet::{libsignal_protocol::double_ratchet::RatchetState}::apply_to_pb::{closure}}]
    Source: 'rust/protocol/src/double_ratchet.rs', lines 165:56-165:89 -/
@[reducible]
def
  double_ratchet.RatchetState.apply_to_pb.closure.Insts.CoreOpsFunctionFnOnceTupleShared0SenderChainChain
  : core.ops.function.FnOnce double_ratchet.RatchetState.apply_to_pb.closure
  double_ratchet.SenderChain proto.storage.session_structure.Chain := {
  call_once :=
    double_ratchet.RatchetState.apply_to_pb.closure.Insts.CoreOpsFunctionFnOnceTupleShared0SenderChainChain.call_once
}

/-- [libsignal_protocol::double_ratchet::{libsignal_protocol::double_ratchet::RatchetState}::apply_to_pb]:
    Source: 'rust/protocol/src/double_ratchet.rs', lines 153:4-168:5 -/
def double_ratchet.RatchetState.apply_to_pb
  (self : double_ratchet.RatchetState)
  (session : proto.storage.SessionStructure) :
  Result proto.storage.SessionStructure
  := do
  let a ← ratchet.keys.RootKey.impl.key self.root_key
  let s ← lift (Array.to_slice a)
  let v ← alloc.slice.Slice.to_vec core.clone.CloneU8 s
  let o ← core.option.Option.as_ref self.sender_chain
  let sender_chain_pb ←
    core.option.Option.map
      double_ratchet.RatchetState.apply_to_pb.closure.Insts.CoreOpsFunctionFnOnceTupleShared0SenderChainChain
      o ()
  ok
    {
      session
        with
        root_key := v,
        previous_counter := self.previous_counter,
        sender_chain := sender_chain_pb,
        receiver_chains := self.receiver_chains
    }

/-- [libsignal_protocol::state::session::{libsignal_protocol::state::session::SessionState}::apply_ratchet_state]:
    Source: 'rust/protocol/src/state/session.rs', lines 670:4-672:5 -/
def state.session.SessionState.apply_ratchet_state
  (self : state.session.SessionState) (ratchet : double_ratchet.RatchetState) :
  Result _root_.Libsignal.RatchetState.state.session.SessionState
  := do
  let ss ← double_ratchet.RatchetState.apply_to_pb ratchet self.session
  ok { session := ss }

/-- [libsignal_protocol::state::session::{libsignal_protocol::state::session::SessionState}::take_pq_ratchet_state]:
    Source: 'rust/protocol/src/state/session.rs', lines 705:4-707:5 -/
def state.session.SessionState.take_pq_ratchet_state
  (self : state.session.SessionState) :
  Result ((alloc.vec.Vec Std.U8) × state.session.SessionState)
  := do
  let (v, v1) ←
    core.mem.take (alloc.vec.Vec.Insts.CoreDefaultDefault Std.U8)
      self.session.pq_ratchet_state
  ok (v, { session := { self.session with pq_ratchet_state := v1 } })

/-- [libsignal_protocol::state::session::{libsignal_protocol::state::session::SessionState}::set_pq_ratchet_state]:
    Source: 'rust/protocol/src/state/session.rs', lines 709:4-711:5 -/
def state.session.SessionState.set_pq_ratchet_state
  (self : state.session.SessionState) (state : alloc.vec.Vec Std.U8) :
  Result _root_.Libsignal.RatchetState.state.session.SessionState
  := do
  ok { session := { self.session with pq_ratchet_state := state } }

end Libsignal.RatchetState
