-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [libsignal_protocol]: type definitions
import Aeneas
import Libsignal.Translated.RatchetState.TypesExternal
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace Libsignal.RatchetState

/-- [libsignal_core::curve::KeyType]
    Source: 'rust/core/src/curve.rs', lines 15:0-15:16
    Name pattern: [libsignal_core::curve::KeyType]
    Visibility: public -/
abbrev libsignal_core.curve.KeyType := _root_.libsignal_core.curve.KeyType

/-- [libsignal_core::curve::CurveError]
    Source: 'rust/core/src/curve.rs', lines 34:0-34:19
    Name pattern: [libsignal_core::curve::CurveError]
    Visibility: public -/
abbrev libsignal_core.curve.CurveError := _root_.libsignal_core.curve.CurveError

/-- [libsignal_core::curve::KeyPair]
    Source: 'rust/core/src/curve.rs', lines 321:0-321:18
    Name pattern: [libsignal_core::curve::KeyPair]
    Visibility: public -/
abbrev libsignal_core.curve.KeyPair := _root_.libsignal_core.curve.KeyPair

/-- [libsignal_protocol::proto::storage::session_structure::PendingKyberPreKey]
    Source: 'target/out/signal.proto.storage.rs', lines 85:4-90:5
    Visibility: public -/
structure proto.storage.session_structure.PendingKyberPreKey where
  pre_key_id : Std.U32
  ciphertext : alloc.vec.Vec Std.U8

/-- [libsignal_protocol::proto::storage::session_structure::PendingPreKey]
    Source: 'target/out/signal.proto.storage.rs', lines 74:4-83:5
    Visibility: public -/
structure proto.storage.session_structure.PendingPreKey where
  pre_key_id : Option Std.U32
  signed_pre_key_id : Std.I32
  base_key : alloc.vec.Vec Std.U8
  timestamp : Std.U64

/-- [libsignal_protocol::proto::storage::session_structure::chain::MessageKey]
    Source: 'target/out/signal.proto.storage.rs', lines 58:8-71:9
    Visibility: public -/
structure proto.storage.session_structure.chain.MessageKey where
  index : Std.U32
  cipher_key : alloc.vec.Vec Std.U8
  mac_key : alloc.vec.Vec Std.U8
  iv : alloc.vec.Vec Std.U8
  seed : alloc.vec.Vec Std.U8

/-- [libsignal_protocol::proto::storage::session_structure::chain::ChainKey]
    Source: 'target/out/signal.proto.storage.rs', lines 51:8-56:9
    Visibility: public -/
structure proto.storage.session_structure.chain.ChainKey where
  index : Std.U32
  key : alloc.vec.Vec Std.U8

/-- [libsignal_protocol::proto::storage::session_structure::Chain]
    Source: 'target/out/signal.proto.storage.rs', lines 38:4-47:5
    Visibility: public -/
structure proto.storage.session_structure.Chain where
  sender_ratchet_key : alloc.vec.Vec Std.U8
  sender_ratchet_key_private : alloc.vec.Vec Std.U8
  chain_key : Option proto.storage.session_structure.chain.ChainKey
  message_keys : alloc.vec.Vec proto.storage.session_structure.chain.MessageKey

/-- [libsignal_protocol::proto::storage::SessionStructure]
    Source: 'target/out/signal.proto.storage.rs', lines 3:0-34:1
    Visibility: public -/
structure proto.storage.SessionStructure where
  session_version : Std.U32
  local_identity_public : alloc.vec.Vec Std.U8
  remote_identity_public : alloc.vec.Vec Std.U8
  root_key : alloc.vec.Vec Std.U8
  previous_counter : Std.U32
  sender_chain : Option proto.storage.session_structure.Chain
  receiver_chains : alloc.vec.Vec proto.storage.session_structure.Chain
  pending_pre_key : Option proto.storage.session_structure.PendingPreKey
  pending_kyber_pre_key : Option
    proto.storage.session_structure.PendingKyberPreKey
  remote_registration_id : Std.U32
  local_registration_id : Std.U32
  alice_base_key : alloc.vec.Vec Std.U8
  pq_ratchet_state : alloc.vec.Vec Std.U8

/-- [libsignal_protocol::ratchet::keys::RootKey]
    Source: 'rust/protocol/src/ratchet/keys.rs', lines 190:0-192:1 -/
abbrev ratchet.keys.RootKey := _root_.libsignal_protocol.ratchet.keys.RootKey

/-- [libsignal_protocol::ratchet::keys::ChainKey]
    Source: 'rust/protocol/src/ratchet/keys.rs', lines 146:0-149:1 -/
abbrev ratchet.keys.ChainKey := _root_.libsignal_protocol.ratchet.keys.ChainKey

/-- [libsignal_protocol::double_ratchet::SenderChain]
    Source: 'rust/protocol/src/double_ratchet.rs', lines 47:0-50:1 -/
structure double_ratchet.SenderChain where
  ratchet_key : libsignal_core.curve.KeyPair
  chain_key : ratchet.keys.ChainKey

/-- [libsignal_protocol::double_ratchet::RatchetState]
    Source: 'rust/protocol/src/double_ratchet.rs', lines 32:0-42:1 -/
structure double_ratchet.RatchetState where
  root_key : ratchet.keys.RootKey
  sender_chain : Option double_ratchet.SenderChain
  receiver_chains : alloc.vec.Vec proto.storage.session_structure.Chain
  previous_counter : Std.U32
  max_forward_jumps : Std.Usize

/-- [libsignal_protocol::state::session::InvalidSessionError]
    Source: 'rust/protocol/src/state/session.rs', lines 27:0-27:63 -/
@[reducible]
def state.session.InvalidSessionError := Str

/-- [libsignal_protocol::double_ratchet::{libsignal_protocol::ratchet::keys::ChainKey}::from_pb::{closure}]
    Source: 'rust/protocol/src/double_ratchet.rs', lines 210:21-210:63 -/
@[reducible]
def double_ratchet.ChainKey.from_pb.closure := Unit

/-- [libsignal_protocol::double_ratchet::{libsignal_protocol::double_ratchet::SenderChain}::from_pb::{closure#1}]
    Source: 'rust/protocol/src/double_ratchet.rs', lines 176:21-176:80 -/
@[reducible]
def double_ratchet.SenderChain.from_pb.closure_1 := Unit

/-- [libsignal_protocol::double_ratchet::{libsignal_protocol::double_ratchet::SenderChain}::from_pb::{closure}]
    Source: 'rust/protocol/src/double_ratchet.rs', lines 174:21-174:79 -/
@[reducible]
def double_ratchet.SenderChain.from_pb.closure := Unit

/-- [libsignal_protocol::double_ratchet::{libsignal_protocol::double_ratchet::RatchetState}::from_pb::{closure#1}]
    Source: 'rust/protocol/src/double_ratchet.rs', lines 133:17-133:52 -/
@[reducible]
def double_ratchet.RatchetState.from_pb.closure_1 := Unit

/-- [libsignal_protocol::double_ratchet::{libsignal_protocol::double_ratchet::RatchetState}::from_pb::{closure}]
    Source: 'rust/protocol/src/double_ratchet.rs', lines 126:21-126:62 -/
@[reducible]
def double_ratchet.RatchetState.from_pb.closure := Unit

/-- [libsignal_protocol::double_ratchet::{libsignal_protocol::double_ratchet::RatchetState}::apply_to_pb::{closure}]
    Source: 'rust/protocol/src/double_ratchet.rs', lines 165:56-165:89 -/
@[reducible]
def double_ratchet.RatchetState.apply_to_pb.closure := Unit

/-- [libsignal_protocol::state::session::SessionState]
    Source: 'rust/protocol/src/state/session.rs', lines 165:0-167:1 -/
structure state.session.SessionState where
  session : proto.storage.SessionStructure

end Libsignal.RatchetState
