-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [libsignal_core]: external functions.
-- This is a template file: rename it to "FunsExternal.lean" and fill the holes.
import Aeneas
import LibsignalCoreTranslation.Types
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048
open libsignal_core

/-- [core::array::equality::{impl core::cmp::PartialEq<[U; N]> for [T]}::eq]:
    Source: '/rustc/library/core/src/array/equality.rs', lines 48:4-48:40
    Name pattern: [core::array::equality::{core::cmp::PartialEq<[@T], [@U; @N]>}::eq]
    Visibility: public -/
@[rust_fun "core::array::equality::{core::cmp::PartialEq<[@T], [@U; @N]>}::eq"]
axiom Slice.Insts.CoreCmpPartialEqArray.eq
  {T : Type} {U : Type} {N : Std.Usize} (cmpPartialEqInst : core.cmp.PartialEq
  T U) :
  Slice T → Array U N → Result Bool

/-- [core::num::niche_types::{impl core::clone::Clone for core::num::niche_types::NonZeroU64Inner}::clone]:
    Source: '/rustc/library/core/src/num/niche_types.rs', lines 17:17-17:22
    Name pattern: [core::num::niche_types::{core::clone::Clone<core::num::niche_types::NonZeroU64Inner>}::clone]
    Visibility: public -/
@[rust_fun
  "core::num::niche_types::{core::clone::Clone<core::num::niche_types::NonZeroU64Inner>}::clone"]
axiom core.num.niche_types.NonZeroU64Inner.Insts.CoreCloneClone.clone
  :
  core.num.niche_types.NonZeroU64Inner → Result
    core.num.niche_types.NonZeroU64Inner

/-- [core::num::niche_types::{impl core::clone::Clone for core::num::niche_types::NonZeroU8Inner}::clone]:
    Source: '/rustc/library/core/src/num/niche_types.rs', lines 17:17-17:22
    Name pattern: [core::num::niche_types::{core::clone::Clone<core::num::niche_types::NonZeroU8Inner>}::clone]
    Visibility: public -/
@[rust_fun
  "core::num::niche_types::{core::clone::Clone<core::num::niche_types::NonZeroU8Inner>}::clone"]
axiom core.num.niche_types.NonZeroU8Inner.Insts.CoreCloneClone.clone
  :
  core.num.niche_types.NonZeroU8Inner → Result
    core.num.niche_types.NonZeroU8Inner

/-- [core::num::nonzero::{core::num::nonzero::NonZero<T, Clause0_NonZeroInner>}::new]:
    Source: '/rustc/library/core/src/num/nonzero.rs', lines 404:4-404:42
    Name pattern: [core::num::nonzero::{core::num::nonzero::NonZero<@T, @Clause0_NonZeroInner>}::new]
    Visibility: public -/
@[rust_fun
  "core::num::nonzero::{core::num::nonzero::NonZero<@T, @Clause0_NonZeroInner>}::new"]
axiom core.num.nonzero.NonZero.new
  {T : Type} {Clause0_NonZeroInner : Type} (ZeroablePrimitiveInst :
  core.num.nonzero.ZeroablePrimitive T Clause0_NonZeroInner) :
  T → Result (Option (core.num.nonzero.NonZero T Clause0_NonZeroInner))

/-- [core::num::nonzero::{core::num::nonzero::NonZero<T, Clause0_NonZeroInner>}::get]:
    Source: '/rustc/library/core/src/num/nonzero.rs', lines 483:4-483:31
    Name pattern: [core::num::nonzero::{core::num::nonzero::NonZero<@T, @Clause0_NonZeroInner>}::get]
    Visibility: public -/
@[rust_fun
  "core::num::nonzero::{core::num::nonzero::NonZero<@T, @Clause0_NonZeroInner>}::get"]
axiom core.num.nonzero.NonZero.get
  {T : Type} {Clause0_NonZeroInner : Type} (ZeroablePrimitiveInst :
  core.num.nonzero.ZeroablePrimitive T Clause0_NonZeroInner) :
  core.num.nonzero.NonZero T Clause0_NonZeroInner → Result T

/-- [core::option::{core::option::Option<T>}::map]:
    Source: '/rustc/library/core/src/option.rs', lines 1157:4-1159:53
    Name pattern: [core::option::{core::option::Option<@T>}::map]
    Visibility: public -/
@[rust_fun "core::option::{core::option::Option<@T>}::map"]
axiom core.option.Option.map
  {T : Type} {U : Type} {F : Type} (opsfunctionFnOnceFTupleTUInst :
  core.ops.function.FnOnce F T U) :
  Option T → F → Result (Option U)

/-- [core::option::{impl core::ops::try_trait::Try for core::option::Option<T>}::branch]:
    Source: '/rustc/library/core/src/option.rs', lines 2779:4-2779:64
    Name pattern: [core::option::{core::ops::try_trait::Try<core::option::Option<@T>>}::branch]
    Visibility: public -/
@[rust_fun
  "core::option::{core::ops::try_trait::Try<core::option::Option<@T>>}::branch"]
axiom core.option.Option.Insts.CoreOpsTry_traitTry.branch
  {T : Type} :
  Option T → Result (core.ops.control_flow.ControlFlow (Option
    core.convert.Infallible) T)

/-- [core::option::{impl core::ops::try_trait::FromResidual<core::option::Option<core::convert::Infallible>> for core::option::Option<T>}::from_residual]:
    Source: '/rustc/library/core/src/option.rs', lines 2793:4-2793:67
    Name pattern: [core::option::{core::ops::try_trait::FromResidual<core::option::Option<@T>, core::option::Option<core::convert::Infallible>>}::from_residual]
    Visibility: public -/
@[rust_fun
  "core::option::{core::ops::try_trait::FromResidual<core::option::Option<@T>, core::option::Option<core::convert::Infallible>>}::from_residual"]
axiom
  core.option.Option.Insts.CoreOpsTry_traitFromResidualOptionInfallible.from_residual
  (T : Type) : Option core.convert.Infallible → Result (Option T)

/-- [core::result::{core::result::Result<T, E>}::ok]:
    Source: '/rustc/library/core/src/result.rs', lines 708:4-711:28
    Name pattern: [core::result::{core::result::Result<@T, @E>}::ok]
    Visibility: public -/
@[rust_fun "core::result::{core::result::Result<@T, @E>}::ok"]
axiom core.result.Result.ok
  {T : Type} {E : Type} : core.result.Result T E → Result (Option T)

/-- [core::result::{impl core::ops::try_trait::Try for core::result::Result<T, E>}::branch]:
    Source: '/rustc/library/core/src/result.rs', lines 2177:4-2177:64
    Name pattern: [core::result::{core::ops::try_trait::Try<core::result::Result<@T, @E>>}::branch]
    Visibility: public -/
@[rust_fun
  "core::result::{core::ops::try_trait::Try<core::result::Result<@T, @E>>}::branch"]
axiom core.result.Result.Insts.CoreOpsTry_traitTry.branch
  {T : Type} {E : Type} :
  core.result.Result T E → Result (core.ops.control_flow.ControlFlow
    (core.result.Result core.convert.Infallible E) T)

/-- [core::result::{impl core::ops::try_trait::FromResidual<core::result::Result<core::convert::Infallible, E>> for core::result::Result<T, F>}::from_residual]:
    Source: '/rustc/library/core/src/result.rs', lines 2192:4-2192:70
    Name pattern: [core::result::{core::ops::try_trait::FromResidual<core::result::Result<@T, @F>, core::result::Result<core::convert::Infallible, @E>>}::from_residual]
    Visibility: public -/
@[rust_fun
  "core::result::{core::ops::try_trait::FromResidual<core::result::Result<@T, @F>, core::result::Result<core::convert::Infallible, @E>>}::from_residual"]
axiom
  core.result.Result.Insts.CoreOpsTry_traitFromResidualResultInfallibleE.from_residual
  (T : Type) {E : Type} {F : Type} (convertFromInst : core.convert.From F E) :
  core.result.Result core.convert.Infallible E → Result (core.result.Result T
    F)

/-- [alloc::string::{impl core::ops::deref::Deref<str> for alloc::string::String}::deref]:
    Source: '/rustc/library/alloc/src/string.rs', lines 2835:4-2835:27
    Name pattern: [alloc::string::{core::ops::deref::Deref<alloc::string::String, str>}::deref]
    Visibility: public -/
@[rust_fun
  "alloc::string::{core::ops::deref::Deref<alloc::string::String, str>}::deref"]
axiom alloc.string.String.Insts.CoreOpsDerefDerefStr.deref
  : String → Result Str

/-- [alloc::vec::{alloc::vec::Vec<T>}::into_boxed_slice]:
    Source: '/rustc/library/alloc/src/vec/mod.rs', lines 1733:4-1733:52
    Name pattern: [alloc::vec::{alloc::vec::Vec<@T>}::into_boxed_slice]
    Visibility: public -/
@[rust_fun "alloc::vec::{alloc::vec::Vec<@T>}::into_boxed_slice"]
axiom alloc.vec.Vec.into_boxed_slice
  {T : Type} (A : Type) : alloc.vec.Vec T → Result (Slice T)

/-- [derive_more::convert::try_from::{derive_more::convert::try_from::TryFromReprError<T>}::new]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/derive_more-2.1.1/src/convert.rs', lines 29:8-29:42
    Name pattern: [derive_more::convert::try_from::{derive_more::convert::try_from::TryFromReprError<@T>}::new]
    Visibility: public -/
@[rust_fun
  "derive_more::convert::try_from::{derive_more::convert::try_from::TryFromReprError<@T>}::new"]
axiom derive_more.convert.try_from.TryFromReprError.new
  {T : Type} : T → Result (derive_more.convert.try_from.TryFromReprError T)

/-- [uuid::builder::{uuid::Uuid}::from_slice]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/uuid-1.19.0/src/builder.rs', lines 287:4-287:54
    Name pattern: [uuid::builder::{uuid::Uuid}::from_slice]
    Visibility: public -/
@[rust_fun "uuid::builder::{uuid::Uuid}::from_slice"]
axiom uuid.builder.Uuid.from_slice
  : Slice Std.U8 → Result (core.result.Result uuid.Uuid uuid.error.Error)

/-- [uuid::builder::{uuid::Uuid}::from_bytes]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/uuid-1.19.0/src/builder.rs', lines 364:4-364:49
    Name pattern: [uuid::builder::{uuid::Uuid}::from_bytes]
    Visibility: public -/
@[rust_fun "uuid::builder::{uuid::Uuid}::from_bytes"]
axiom uuid.builder.Uuid.from_bytes : Array Std.U8 16#usize → Result uuid.Uuid

/-- [uuid::{uuid::Uuid}::as_bytes]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/uuid-1.19.0/src/lib.rs', lines 790:4-790:42
    Name pattern: [uuid::{uuid::Uuid}::as_bytes]
    Visibility: public -/
@[rust_fun "uuid::{uuid::Uuid}::as_bytes"]
axiom uuid.Uuid.as_bytes : uuid.Uuid → Result (Array Std.U8 16#usize)

/-- [libsignal_core::curve::{libsignal_core::curve::PublicKey}::deserialize]:
    Source: 'rust/core/src/curve.rs', lines 84:4-105:5
    Visibility: public -/
axiom curve.PublicKey.deserialize
  :
  Slice Std.U8 → Result (core.result.Result curve.PublicKey curve.CurveError)

/-- [libsignal_core::curve::{libsignal_core::curve::PublicKey}::verify_signature_for_multipart_message]:
    Source: 'rust/core/src/curve.rs', lines 138:4-151:5
    Visibility: public -/
axiom curve.PublicKey.verify_signature_for_multipart_message
  : curve.PublicKey → Slice (Slice Std.U8) → Slice Std.U8 → Result Bool

/-- [libsignal_core::curve::{libsignal_core::curve::PublicKey}::is_torsion_free]:
    Source: 'rust/core/src/curve.rs', lines 165:4-174:5 -/
axiom curve.PublicKey.is_torsion_free : curve.PublicKey → Result Bool

/-- [libsignal_core::curve::{impl core::convert::TryFrom<&'_0 [u8], libsignal_core::curve::CurveError> for libsignal_core::curve::PublicKey}::try_from]:
    Source: 'rust/core/src/curve.rs', lines 196:4-198:5
    Visibility: public -/
axiom curve.PublicKey.Insts.CoreConvertTryFromShared0SliceU8CurveError.try_from
  :
  Slice Std.U8 → Result (core.result.Result curve.PublicKey curve.CurveError)

/-- [libsignal_core::curve::{libsignal_core::curve::PrivateKey}::deserialize]:
    Source: 'rust/core/src/curve.rs', lines 242:4-251:5
    Visibility: public -/
axiom curve.PrivateKey.deserialize
  :
  Slice Std.U8 → Result (core.result.Result curve.PrivateKey
    curve.CurveError)

/-- [libsignal_core::curve::{libsignal_core::curve::PrivateKey}::public_key]:
    Source: 'rust/core/src/curve.rs', lines 259:4-267:5
    Visibility: public -/
axiom curve.PrivateKey.public_key
  :
  curve.PrivateKey → Result (core.result.Result curve.PublicKey
    curve.CurveError)

/-- [libsignal_core::curve::{libsignal_core::curve::PrivateKey}::calculate_signature]:
    Source: 'rust/core/src/curve.rs', lines 275:4-281:5
    Visibility: public -/
axiom curve.PrivateKey.calculate_signature
  {R : Type} (rand_core_1CryptoRngInst : rand_core_1.CryptoRng R)
  (randrngRngInst : rand.rng.Rng R) :
  curve.PrivateKey → Slice Std.U8 → R → Result ((core.result.Result
    (Slice Std.U8) curve.CurveError) × R)

/-- [libsignal_core::curve::{libsignal_core::curve::PrivateKey}::calculate_signature_for_multipart_message]:
    Source: 'rust/core/src/curve.rs', lines 283:4-294:5
    Visibility: public -/
axiom curve.PrivateKey.calculate_signature_for_multipart_message
  {R : Type} (rand_core_1CryptoRngInst : rand_core_1.CryptoRng R)
  (randrngRngInst : rand.rng.Rng R) :
  curve.PrivateKey → Slice (Slice Std.U8) → R → Result
    ((core.result.Result (Slice Std.U8) curve.CurveError) × R)

/-- [libsignal_core::curve::{libsignal_core::curve::PrivateKey}::calculate_agreement]:
    Source: 'rust/core/src/curve.rs', lines 296:4-309:5
    Visibility: public -/
axiom curve.PrivateKey.calculate_agreement
  :
  curve.PrivateKey → curve.PublicKey → Result (core.result.Result (Slice
    Std.U8) curve.CurveError)

/-- [libsignal_core::curve::{impl core::convert::TryFrom<&'_0 [u8], libsignal_core::curve::CurveError> for libsignal_core::curve::PrivateKey}::try_from]:
    Source: 'rust/core/src/curve.rs', lines 315:4-317:5
    Visibility: public -/
axiom
  curve.PrivateKey.Insts.CoreConvertTryFromShared0SliceU8CurveError.try_from
  :
  Slice Std.U8 → Result (core.result.Result curve.PrivateKey
    curve.CurveError)

/-- [libsignal_core::curve::{libsignal_core::curve::KeyPair}::generate]:
    Source: 'rust/core/src/curve.rs', lines 327:4-341:5
    Visibility: public -/
axiom curve.KeyPair.generate
  {R : Type} (randrngRngInst : rand.rng.Rng R) (rand_core_1CryptoRngInst :
  rand_core_1.CryptoRng R) :
  R → Result (curve.KeyPair × R)

/-- [libsignal_core::curve::{libsignal_core::curve::KeyPair}::calculate_signature]:
    Source: 'rust/core/src/curve.rs', lines 362:4-368:5
    Visibility: public -/
axiom curve.KeyPair.calculate_signature
  {R : Type} (rand_core_1CryptoRngInst : rand_core_1.CryptoRng R)
  (randrngRngInst : rand.rng.Rng R) :
  curve.KeyPair → Slice Std.U8 → R → Result ((core.result.Result (Slice
    Std.U8) curve.CurveError) × R)

/-- [libsignal_core::curve::{libsignal_core::curve::KeyPair}::calculate_agreement]:
    Source: 'rust/core/src/curve.rs', lines 370:4-372:5
    Visibility: public -/
axiom curve.KeyPair.calculate_agreement
  :
  curve.KeyPair → curve.PublicKey → Result (core.result.Result (Slice
    Std.U8) curve.CurveError)

